services:
  db:
    image: postgres:15
    container_name: nyc_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nyc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nyc_network

  etl:
    build: .
    container_name: nyc_etl
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./:/app
    working_dir: /app
    command: ["uv", "run", "-m", "etl.pipeline"]
    networks:
      - nyc_network

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: nyc_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - nyc_network

volumes:
  pgdata:
  pgadmin_data:

networks:
  nyc_network:
    driver: bridge
